artifacts_root: artifacts

data_loader:
  data_path: artifacts/data
  file_types: "*.pdf"

data_splitter:
  chunk_size: 500
  chunk_overlap: 50

vectorization:
  model_name: sentence-transformers/all-MiniLM-L6-v2
  index_name: medical-chatbot
  namespace: medicalChatBot
  encoder_name: sentence-transformers/all-MiniLM-L6-v2
  encoder_platform: HuggingFace
  num_of_documnets: 3

llm_model:
  implementation: LlamaCpp
